# Generated by Django 3.0.5 on 2020-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
