# Generated by Django 3.0.5 on 2020-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_request_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
