version: '3.7'

services:
  web:
    build: .
    container_name: starnavi_spasenko_test
    command: sh -c "python manage.py migrate
      && python manage.py initadmin --username admin --password admin
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./.config.automated_bot:/code/.config.automated_bot
      - ./automated_bot.py:/code/automated_bot.py
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5437:5432
    env_file:
      - .env.db

volumes:
  postgres_data: